[package]
name = "disguised-webqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest-impersonate = { version = "0.11", features = ["websocket"] }
tungstenite = "0.23.0"
futures-util = "0.3.30"
